### ISSUE TITLE
Minimum GPU requirements for hello world example

### ISSUE THREAD

**Issue by sharlec** [AlibabaPAI/llumnix#1]
Hello,

I am trying to setup the hello world example and I got the error message as: 
```
enable migrate
2024-06-08 04:09:11,885 INFO worker.py:1452 -- Connecting to existing Ray cluster at address: 10.218.163.85:6379...
2024-06-08 04:09:11,888 INFO worker.py:1636 -- Connected to Ray cluster.
Traceback (most recent call last):
  File "/opt/conda/envs/artifact/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/artifact/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/llumnix/vllm/entrypoints/api_server.py", line 167, in <module>
    engine_manager = LLMEngineManager.from_engine_args(engine_args)
  File "/workspace/llumnix/vllm/engine/llm_engine_manager.py", line 621, in from_engine_args
    distributed_init_method, placement_group = initialize_cluster(
  File "/workspace/llumnix/vllm/engine/ray_utils.py", line 97, in initialize_cluster
    raise ValueError(
ValueError: The number of required GPUs exceeds the total number of available GPUs in the cluster.
```

The README suggests to have 16 GPUs, what is the minimum GPUs for this example and where to change the config?

**Comment by ZeldaHuang** [comment]
You can change config in `artifact/0_getting_started/config/serving_exp_test`. Our evaluation needs a 16-GPU cluster, you can reduce `instance_parallel_size` to run with fewer gpus.
